config/routes.rb
Rails.application.routes.draw do
  get 'trades/index'

  get 'trades/show'

  post 'trades/check_trades'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
class Trade < ApplicationRecord
  require "csv"

  def self.check_trades(liqui_response, poloniex_response)

    # calls to the apis are made on in the controller and passed down
    return if liqui_response["success"] == 0
    return if poloniex_response.parsed_response == 0
    liqui_sell = liqui_response["eth_usdt"]["asks"][0]
    liqui_buy = liqui_response["eth_usdt"]["bids"][0]
    poloniex_sell = [(poloniex_response["asks"][0][0]).to_f, poloniex_response["asks"][0][1]]
    poloniex_buy = [(poloniex_response["bids"][0][0]).to_f, poloniex_response["bids"][0][1]]

    top_trades = { sells:
      { sell_on_liqui: liqui_buy,
        sell_on_poloniex: poloniex_buy },
        buys:
        { buy_on_liqui: liqui_sell,
          buy_on_poloniex: poloniex_sell}
        }
    profitable_trade(top_trades)
  end

  def self.find_highest_sell(sells)
    (sells.max_by{|k,v| v})
  end

  def self.find_lowest_buy(buys)
    (buys.min_by{|k,v| v})
  end

  def self.profitable_trade(trades)
    # determines which exchange has the highest sell and lowest buy
    # then we check if the difference is in our margin
    high_sell = find_highest_sell(trades[:sells])
    low_buy = find_lowest_buy(trades[:buys])
    rate_above =  high_sell[1][0] - (low_buy[1][0] * ((1 + 0.0025)/ ( 1 - 0.0026)) + (25+0.01*low_buy[1][0])/8)
    puts rate_above
    if high_sell[1][0] >= (low_buy[1][0] * ((1 + 0.0025)/ ( 1 - 0.0026)) + (25+0.01*low_buy[1][0])/8)
      # if there is an opportunity we check to see which one has the lowest volume
      # this becomes the highest amount we can buy/sell
      find_highest_amount([high_sell, low_buy, rate_above])
    end
  end

  def self.find_highest_amount(data)
    # data is in a format of [sellexchange: [rate, eth_amount], buyexchang: [rate, eth_amount]]
    if (data[0][1][1] < data[1][1][1])
      Trade.create(sell_exchange: data[0][0], sell_rate: data[0][1][0], buy_exchange: data[1][0], buy_rate: data[1][1][0], amount: data[0][1][1], rate_above_break_even: data[2])
    else
      Trade.create(sell_exchange: data[0][0], sell_rate: data[0][1][0], buy_exchange: data[1][0], buy_rate: data[1][1][0], amount: data[1][1][1], rate_above_break_even: data[2])
    end
  end

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |trade|
        csv << trade.attributes.values
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  def index
    @trades = Trade.all
    respond_to do |format|
      format.html
      format.csv { send_data @trades.to_csv }
    end
  end

  def show
  end

  def check_trades
    x = 2400
    x.times do
      begin
        liqui_response = HTTParty.get('https://api.liqui.io/api/3/depth/eth_usdt?limit=10')
      rescue Errno::ETIMEDOUT, Net::OpenTimeout, Errno::ECONNRESET, OpenSSL::SSL::SSLError
        puts "liqui rescue"
        retry
      end
      begin
        poloniex_response = HTTParty.get('https://poloniex.com/public?command=returnOrderBook&currencyPair=USDT_ETH&depth=10')
      rescue Errno::ETIMEDOUT, Net::OpenTimeout, Errno::ECONNRESET, OpenSSL::SSL::SSLError
        puts "poloniex rescue"
        retry
      end
      puts "///// #{x} ///////"
      x -= 1;
      Trade.check_trades(liqui_response, poloniex_response)

      sleep(rand(5..9))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmgScraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trades/index.html.erb
<h1 style="text-align: center">Tactical Crypto Holdings</h1>
<div class="start">
  <%= link_to 'Check Trades', trades_check_trades_path, method: :post %>
</div>

<p>
  Download
  <%= link_to "CSV", trades_index_path(format: "csv") %>
</p>

<table>
  <tr class="header">
    <td>ID</td>
    <td>Sell Exchnage</td>
    <td>Sell Rate</td>
    <td>Buy Exchange</td>
    <td>Buy Rate</td>
    <td>Volume (ETH)</td>
    <td>Delta(above break even)</td>
    <td>Gain</td>
  </tr>
  <% @trades.each do |trade| %>
    <tr>
      <td><%= trade.id %></td>
      <td><%= trade.sell_exchange %></td>
      <td><%= trade.sell_rate %></td>
      <td><%= trade.buy_exchange %></td>
      <td><%= trade.buy_rate %></td>
      <td><%= trade.amount %></td>
      <td><%= trade.rate_above_break_even %></td>
      <td><%= trade.amount * trade.rate_above_break_even %></td>
    </tr>
  <% end %>
</table>

app/views/trades/show.html.erb
<h1>Trades#show</h1>
<p>Find me in app/views/trades/show.html.erb</p>